name: CI Spring Boot

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Java 17 installieren
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Maven Build
        run: mvn clean package
